name: Nhplugin
version: ${project.version}
main: me.bdx.nhplugin.Nhplugin
api-version: 1.16
depend: [Vault]
softdepend:
  - Managerapi

commands:

  js:
    description: use one of the javascript commands
    usage: /<command> <name> <args>
    aliases: [javascript]

  dummycommand:
    description: Empty commands which can be listened for
    usage: /<command>
    aliases:
      - testing

  reloadscripts:
    description: Reloads the current scripts
    usage: /<command>

permissions:
  nh.*:
    children:
      nh.cmd: true
      nh.nt: true
      nh.js: false
      nh.registercommands: false
      nh.reloadscripts: true
